"""
fhir_export.py
===============
Packages a composite risk result as an HL7 FHIR "Observation" resource --
the standard format EHR systems (Epic, Cerner, etc.) expect for
structured clinical data exchange. This is the piece of "shipping to
existing medical systems" that's actually just code; the rest (below)
isn't.

This does NOT send anything anywhere -- it only builds the JSON payload.
Actually transmitting it requires a specific hospital's FHIR API
endpoint, an OAuth2 SMART-on-FHIR credential, and their IT team's
sign-off. That's a partnership/procurement process, not something any
codebase can complete unilaterally.

Usage
-----
    from fhir_export import build_risk_observation
    payload = build_risk_observation(
        patient_id="12345",
        p_tab=0.86, p_ecg=0.42, p_ct=0.37,
        risk_percentage=61.4, risk_tier="Moderate (35-69%)",
    )
    # payload is now a plain dict, ready for json.dumps() and a POST to
    # a real FHIR server's /Observation endpoint (once you have one).
"""

from datetime import datetime, timezone
from typing import Optional


# LOINC code for "Stroke risk score" (used generically -- consult your
# integration partner's IT/informatics team on whether a more specific
# or locally-defined code is expected; this is a reasonable default).
_LOINC_STROKE_RISK_CODE = "75740-9"


def build_risk_observation(
    patient_id: str,
    p_tab: float,
    p_ecg: float,
    p_ct: float,
    risk_percentage: float,
    risk_tier: str,
    observation_id: Optional[str] = None,
) -> dict:
    """
    Builds a FHIR R4 Observation resource (as a plain Python dict) for
    this system's composite stroke-risk output, with the three
    sub-model scores attached as `component` entries -- so a clinician
    viewing this in an EHR can see not just the composite number, but
    what it was made of.
    """
    now_iso = datetime.now(timezone.utc).isoformat()

    resource = {
        "resourceType": "Observation",
        "status": "final",
        "category": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                        "code": "risk-assessment",
                        "display": "Risk Assessment",
                    }
                ]
            }
        ],
        "code": {
            "coding": [
                {
                    "system": "http://loinc.org",
                    "code": _LOINC_STROKE_RISK_CODE,
                    "display": "Stroke risk assessment score",
                }
            ],
            "text": "Composite silent-stroke early-warning risk score",
        },
        "subject": {"reference": f"Patient/{patient_id}"},
        "effectiveDateTime": now_iso,
        "issued": now_iso,
        "valueQuantity": {
            "value": round(risk_percentage, 2),
            "unit": "%",
            "system": "http://unitsofmeasure.org",
            "code": "%",
        },
        "interpretation": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                        "code": _tier_to_interpretation_code(risk_tier),
                        "display": risk_tier,
                    }
                ]
            }
        ],
        "component": [
            _component("Tabular clinical risk sub-score", p_tab),
            _component("ECG-derived risk sub-score", p_ecg),
            _component("CT-derived risk sub-score", p_ct),
        ],
        "note": [
            {
                "text": (
                    "Generated by an automated risk-screening tool. This is "
                    "NOT a diagnosis and does not replace clinical evaluation. "
                    "Composite score = 0.35*tabular + 0.35*ECG + 0.30*CT."
                )
            }
        ],
    }

    if observation_id:
        resource["id"] = observation_id

    return resource


def _component(label: str, probability: float) -> dict:
    return {
        "code": {"text": label},
        "valueQuantity": {
            "value": round(probability * 100, 2),
            "unit": "%",
            "system": "http://unitsofmeasure.org",
            "code": "%",
        },
    }


def _tier_to_interpretation_code(risk_tier: str) -> str:
    """Maps our tier strings to the closest standard HL7 interpretation code."""
    tier_lower = risk_tier.lower()
    if "high" in tier_lower:
        return "HH"  # "critically high"
    if "moderate" in tier_lower:
        return "H"   # "high" (relative to normal)
    return "N"       # "normal"


if __name__ == "__main__":
    import json

    example = build_risk_observation(
        patient_id="example-patient-001",
        p_tab=0.861,
        p_ecg=0.42,
        p_ct=0.37,
        risk_percentage=61.4,
        risk_tier="Moderate (35-69%)",
    )
    print(json.dumps(example, indent=2))
